# Generated by Django 5.0.2 on 2024-02-11 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé')], default='closed', max_length=10)),
                ('opening_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('difficulty_level', models.CharField(max_length=20)),
                ('personal_progress', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('difficulty_level', models.CharField(max_length=20)),
                ('personal_progress', models.CharField(max_length=50)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetPython.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetPython.student')),
            ],
        ),
        migrations.CreateModel(
            name='FormFirstLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login_time', models.DateTimeField(auto_now_add=True)),
                ('some_field', models.CharField(max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProjetPython.student')),
            ],
        ),
    ]
